title: Guru's Data World
logo:![IMG_20231105_112644](https://github.com/gurulokeshv/GuruDataTalks/assets/43316617/486bb907-8658-4e0d-bb6f-2cf322da33ea)

#show_downloads: true
theme: jekyll-theme-minimal
